version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  api:
    build:
      context: .
      dockerfile: ./Dockerfile.${ENVIRONMENT}
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
    env_file:
      - .env.${ENVIRONMENT}
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --noinput
      && /usr/local/bin/gunicorn chatapp.wsgi:application -w 2 -b :8000 --reload"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
