version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.${ENVIRONMENT}
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
    env_file:
      - .env.${ENVIRONMENT}
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --noinput
      && uvicorn --host 0.0.0.0 --port 8000 --debug chatapp.asgi:application"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
