version: '3'

services:
  test:
    build:
      context: .
      dockerfile: ./Dockerfile.${ENVIRONMENT}
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
    env_file:
      - .env.${ENVIRONMENT}
    command: >
      bash -c "coverage run --source='.' manage.py test -s
      && coverage html
      && python3 -m http.server 9999"
    volumes:
      - .:/code
    ports:
      - 8001:8001
